# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Safety' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Safety
  pod "EVReflection"
  pod 'ZIPFoundation'
  pod "TraceLog"
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseDatabase'
  pod 'FirebaseMessaging'
end
